
export const HOST = `http://localhost:8080`
export const LOGIN_REQ = "LOGIN_REQ"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_REQ = "REGISTER_REQ"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGOUT_REQ = "LOGOUT_REQ"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

//student
export const GET_STUDENT_REQ = "GET_STUDENT_REQ"
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
export const GET_STUDENT_FAIL = "GET_STUDENT_FAIL"

export const ADD_STUDENT_REQ = "ADD_STUDENT_REQ"
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL"

export const UPDATE_STUDENT_REQ = "UPDATE_STUDENT_REQ"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL"

export const DELETE_STUDENT_REQ = "DELETE_STUDENT_REQ"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL"

export const PAY_COURSE_REQ = "PAY_COURSE_REQ"
export const PAY_COURSE_SUCCESS = "PAY_COURSE_SUCCESS"
export const PAY_COURSE_FAIL = "PAY_COURSE_FAIL"

//teacher
export const GET_TEACHER_REQ = "GET_TEACHER_REQ"
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS"
export const GET_TEACHER_FAIL = "GET_TEACHER_FAIL"

export const ADD_TEACHER_REQ = "ADD_TEACHER_REQ"
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS"
export const ADD_TEACHER_FAIL = "ADD_TEACHER_FAIL"

export const UPDATE_TEACHER_REQ = "UPDATE_TEACHER_REQ"
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS"
export const UPDATE_TEACHER_FAIL = "UPDATE_TEACHER_FAIL"

export const DELETE_TEACHER_REQ = "DELETE_TEACHER_REQ"
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS"
export const DELETE_TEACHER_FAIL = "DELETE_TEACHER_FAIL"

//course 
export const GET_COURSE_REQ = "GET_COURSE_REQ"
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS"
export const GET_COURSE_FAIL = "GET_COURSE_FAIL"

export const ADD_COURSE_REQ = "ADD_COURSE_REQ"
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS"
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL"

export const UPDATE_COURSE_REQ = "UPDATE_COURSE_REQ"
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS"
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL"

export const DELETE_COURSE_REQ = "DELETE_COURSE_REQ"
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS"
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL"

//class
export const GET_CLASS_REQ = "GET_CLASS_REQ"
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS"
export const GET_CLASS_FAIL = "GET_CLASS_FAIL"

export const ADD_CLASS_REQ = "ADD_CLASS_REQ"
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS"
export const ADD_CLASS_FAIL = "ADD_CLASS_FAIL"

export const UPDATE_CLASS_REQ = "UPDATE_CLASS_REQ"
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS"
export const UPDATE_CLASS_FAIL = "UPDATE_CLASS_FAIL"

export const DELETE_CLASS_REQ = "DELETE_CLASS_REQ"
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS"
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL"

export const GET_CLASS_BY_ID_COURSE_REQ="GET_CLASS_BY_ID_COURSE_REQ"
export const GET_CLASS_BY_ID_COURSE_SUCCESS="GET_CLASS_BY_ID_COURSE_SUCCESS"
export const GET_CLASS_BY_ID_COURSE_FAIL="GET_CLASS_BY_ID_COURSE_FAIL"